name: E2E workflow

on:
  repository_dispatch:
    types: [on-demand-test]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit:
        description: Original repo commit SHA
        required: false

jobs:
  # example job showing the Netlify information
  show-event:
    runs-on: ubuntu-latest
    steps:
      - run: echo "SHA ${{ github.event.client_payload.sha }}"